{{- if .Values.kubedns }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-mesh-coredns
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: coredns
    chart: {{ include "traefikMesh.chartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end}}
