---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-mesh-identity
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: identity
    chart: {{ include "traefikMesh.chartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-mesh-identity
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: identity
    chart: {{ include "traefikMesh.chartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-mesh-identity
subjects:
  - kind: ServiceAccount
    name: traefik-mesh-identity
    namespace: {{ .Release.Namespace }}
