---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jaeger
  labels:
    app: jaeger
    chart: {{ include "traefikMesh.chartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
