---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-mesh-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: controller
    chart: {{ include "traefikMesh.chartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
automountServiceAccountToken: true
