---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    app: maesh
    component: prometheus
    chart: {{ include "traefikMesh.chartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    app: maesh
    component: prometheus
    chart: {{ include "traefikMesh.chartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-k8s
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: prometheus
    chart: {{ include "traefikMesh.chartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-k8s
  namespace: {{ .Release.Namespace }}
  labels:
    app: maesh
    component: grafana
    chart: {{ include "traefikMesh.chartLabel" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
